"""schema baseline

Revision ID: 6e1829d5f417
Revises:
Create Date: 2026-08-24 09:46:33.094260

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e1829d5f417"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("givenname", sa.String(), nullable=True),
        sa.Column("birthyear", sa.Integer(), nullable=True),
        sa.Column("deathyear", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("composer", sa.Boolean(), nullable=False),
        sa.Column("conductor", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("surname", "givenname"),
    )
    op.create_table(
        "auth_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(), nullable=True),
        sa.Column("fired_at", sa.DateTime(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "booking_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("booking_type", sa.String(), nullable=False),
        sa.Column("position_type", sa.String(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("fee", sa.Integer(), nullable=False),
        sa.Column("notified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("booking_type IN ('book', 'unbook')"),
        sa.CheckConstraint("position_type IN ('instruments', 'voices', 'choirjobs')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "booking_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notbooked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "user_id"),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("position_type", sa.String(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("fee", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("position_type IN ('instruments', 'voices', 'choirjobs')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "user_id"),
        sa.UniqueConstraint(
            "performance_id", "user_id", "position_type", "position_id"
        ),
    )
    op.create_table(
        "choirjobs",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "client_user_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("string", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "instruments",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "locations",
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "oauth2_bindings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column("remote_name", sa.String(), nullable=False),
        sa.Column("local_id", sa.Integer(), nullable=False),
        sa.Column("bound_at", sa.DateTime(), nullable=False),
        sa.Column("lastuse_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "remote_id"),
    )
    op.create_table(
        "ordinariumwork_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ordinariumwork_id", sa.Integer(), nullable=False),
        sa.Column("position_type", sa.String(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("position_type IN ('instruments', 'voices')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ordinariumwork_id", "position_type", "position_id"),
    )
    op.create_table(
        "ordinariumworks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("demanding", sa.Boolean(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "artist_id"),
    )
    # No PrimaryKeyConstraint here on purpose: the real legacy table has no
    # PK at all (see tests/fixtures/legacy_schema.sql -- plain columns, no
    # "primary key"). The SQLAlchemy model declares email as primary_key=True
    # purely for the ORM's identity map/delete() (see
    # app/db/models/password_reset_token.py's docstring) -- letting
    # autogenerate turn that into a real Postgres PrimaryKeyConstraint would
    # be a structural addition beyond the 1:1 transfer, not present in
    # Legacy. Manually stripped from the autogenerated op.create_table() call.
    op.create_table(
        "password_reset_tokens",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index(
        "password_resets_email_index", "password_reset_tokens", ["email"], unique=False
    )
    op.create_table(
        "performance_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("position_type", sa.String(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("position_type IN ('instruments', 'voices', 'choirjobs')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "position_type", "position_id"),
    )
    op.create_table(
        "performance_proprium",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("propriumelement_id", sa.Integer(), nullable=False),
        sa.Column("propriumwork_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "propriumelement_id"),
    )
    op.create_table(
        "performance_rehearsals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("performance_id", sa.Integer(), nullable=False),
        sa.Column("schedule", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("performance_id", "schedule"),
    )
    op.create_table(
        "performances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule", sa.DateTime(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("ordinariumwork_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("choirjob_defaultfee", sa.Integer(), nullable=False),
        sa.Column("instrument_defaultfee", sa.Integer(), nullable=False),
        sa.Column("voice_defaultfee", sa.Integer(), nullable=False),
        sa.Column("extracost_amount", sa.Integer(), nullable=True),
        sa.Column("extracost_description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personal_access_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tokenable_type", sa.String(), nullable=False),
        sa.Column("tokenable_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("abilities", sa.String(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "personal_access_tokens_token_unique",
        "personal_access_tokens",
        ["token"],
        unique=True,
    )
    op.create_index(
        "personal_access_tokens_tokenable_type_tokenable_id_index",
        "personal_access_tokens",
        ["tokenable_type", "tokenable_id"],
        unique=False,
    )
    op.create_table(
        "propriumelements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "propriumworks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("demanding", sa.Boolean(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "artist_id"),
    )
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_ip", sa.String(), nullable=False),
        sa.Column("client_ips", sa.String(), nullable=True),
        sa.Column("client_user_agent_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("request_method", sa.String(), nullable=False),
        sa.Column("request_path", sa.String(), nullable=False),
        sa.Column("request_input", sa.String(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_content", sa.String(), nullable=True),
        sa.Column("memory_usage", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kasten", sa.String(), nullable=True),
        sa.Column("boxnr", sa.String(), nullable=True),
        sa.Column("auch", sa.String(), nullable=True),
        sa.Column("inhalt", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("givenname", sa.String(), nullable=True),
        sa.Column("geboren", sa.Integer(), nullable=True),
        sa.Column("gestorben", sa.Integer(), nullable=True),
        sa.Column("werk", sa.String(), nullable=True),
        sa.Column("teil", sa.String(), nullable=True),
        sa.Column("sparte", sa.String(), nullable=True),
        sa.Column("verz", sa.String(), nullable=True),
        sa.Column("jahr", sa.Integer(), nullable=True),
        sa.Column("part1verl", sa.String(), nullable=True),
        sa.Column("part1art", sa.String(), nullable=True),
        sa.Column("part1zust", sa.String(), nullable=True),
        sa.Column("part1anz", sa.Integer(), nullable=False),
        sa.Column("part2verl", sa.String(), nullable=True),
        sa.Column("part2art", sa.String(), nullable=True),
        sa.Column("part2zust", sa.String(), nullable=True),
        sa.Column("part2anz", sa.Integer(), nullable=False),
        sa.Column("klausz1verl", sa.String(), nullable=True),
        sa.Column("klausz1art", sa.String(), nullable=True),
        sa.Column("klausz1zust", sa.String(), nullable=True),
        sa.Column("klausz1anz", sa.Integer(), nullable=False),
        sa.Column("klausz2verl", sa.String(), nullable=True),
        sa.Column("klausz2art", sa.String(), nullable=True),
        sa.Column("klausz2zust", sa.String(), nullable=True),
        sa.Column("klausz2anz", sa.Integer(), nullable=False),
        sa.Column("chorpart1verl", sa.String(), nullable=True),
        sa.Column("chorpart1art", sa.String(), nullable=True),
        sa.Column("chorpart1zust", sa.String(), nullable=True),
        sa.Column("chorpart1anz", sa.Integer(), nullable=False),
        sa.Column("chorpart2verl", sa.String(), nullable=True),
        sa.Column("chorpart2art", sa.String(), nullable=True),
        sa.Column("chorpart2zust", sa.String(), nullable=True),
        sa.Column("chorpart2anz", sa.Integer(), nullable=False),
        sa.Column("stsoprverl", sa.String(), nullable=True),
        sa.Column("stsoprart", sa.String(), nullable=True),
        sa.Column("stsoprzust", sa.String(), nullable=True),
        sa.Column("stsopranz", sa.Integer(), nullable=False),
        sa.Column("staltverl", sa.String(), nullable=True),
        sa.Column("staltart", sa.String(), nullable=True),
        sa.Column("staltzust", sa.String(), nullable=True),
        sa.Column("staltanz", sa.Integer(), nullable=False),
        sa.Column("sttenverl", sa.String(), nullable=True),
        sa.Column("sttenart", sa.String(), nullable=True),
        sa.Column("sttenzust", sa.String(), nullable=True),
        sa.Column("sttenanz", sa.Integer(), nullable=False),
        sa.Column("stbassverl", sa.String(), nullable=True),
        sa.Column("stbassart", sa.String(), nullable=True),
        sa.Column("stbasszust", sa.String(), nullable=True),
        sa.Column("stbassanz", sa.Integer(), nullable=False),
        sa.Column("orgelverl", sa.String(), nullable=True),
        sa.Column("orgelart", sa.String(), nullable=True),
        sa.Column("orgelzust", sa.String(), nullable=True),
        sa.Column("orgelanz", sa.Integer(), nullable=False),
        sa.Column("orchverl", sa.String(), nullable=True),
        sa.Column("orchart", sa.String(), nullable=True),
        sa.Column("orchzust", sa.String(), nullable=True),
        sa.Column("violine1", sa.Integer(), nullable=False),
        sa.Column("violine2", sa.Integer(), nullable=False),
        sa.Column("viola", sa.Integer(), nullable=False),
        sa.Column("cello", sa.Integer(), nullable=False),
        sa.Column("contrabass", sa.Integer(), nullable=False),
        sa.Column("floete1", sa.Integer(), nullable=False),
        sa.Column("floete2", sa.Integer(), nullable=False),
        sa.Column("floete3", sa.Integer(), nullable=False),
        sa.Column("oboe1", sa.Integer(), nullable=False),
        sa.Column("oboe2", sa.Integer(), nullable=False),
        sa.Column("klarinette1", sa.Integer(), nullable=False),
        sa.Column("klarinette2", sa.Integer(), nullable=False),
        sa.Column("fagott1", sa.Integer(), nullable=False),
        sa.Column("fagott2", sa.Integer(), nullable=False),
        sa.Column("kontrafagott", sa.Integer(), nullable=False),
        sa.Column("trombalt", sa.Integer(), nullable=False),
        sa.Column("trombten", sa.Integer(), nullable=False),
        sa.Column("trombbass", sa.Integer(), nullable=False),
        sa.Column("corno1", sa.Integer(), nullable=False),
        sa.Column("corno2", sa.Integer(), nullable=False),
        sa.Column("trompete1", sa.Integer(), nullable=False),
        sa.Column("trompete2", sa.Integer(), nullable=False),
        sa.Column("trompete3", sa.Integer(), nullable=False),
        sa.Column("pauke", sa.Integer(), nullable=False),
        sa.Column("soinstr1art", sa.String(), nullable=True),
        sa.Column("soinstr1anz", sa.Integer(), nullable=False),
        sa.Column("soinstr2art", sa.String(), nullable=True),
        sa.Column("soinstr2anz", sa.Integer(), nullable=False),
        sa.Column("soinstr3art", sa.String(), nullable=True),
        sa.Column("soinstr3anz", sa.Integer(), nullable=False),
        sa.Column("soinstr4art", sa.String(), nullable=True),
        sa.Column("soinstr4anz", sa.Integer(), nullable=False),
        sa.Column("bemerkung", sa.String(), nullable=True),
        sa.Column("zusatznoten", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("chorpart1art IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("chorpart2art IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint(
            "inhalt IN ('Orchestermaterial', 'Chormaterial', "
            "'Orch-/Chormaterial', 'Klavierauszug', 'Orgelauszug', "
            "'Partitur', 'Singstimme')"
        ),
        sa.CheckConstraint("klausz1art IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("klausz2art IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("orchart IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("orgelart IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("part1art IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("part2art IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint(
            "sparte IN ('Advent/Weihnacht', 'Bundeshymne', 'Chor', 'Lied', "
            "'Messe', 'Oratorium', 'Orch/Harfe', 'Orch/Orgel', "
            "'Orch/Sakral', 'Orch/Sol/Chor', 'Orchester', 'Passion', "
            "'Sakral', 'Sakral/Solo', 'Symphonie', 'Volkslied')"
        ),
        sa.CheckConstraint("staltart IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("stbassart IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("stsoprart IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.CheckConstraint("sttenart IN ('Original', 'Kopie', 'Original/Kopie')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sent_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from", sa.String(), nullable=True),
        sa.Column("to", sa.String(), nullable=True),
        sa.Column("cc", sa.String(), nullable=True),
        sa.Column("bcc", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("headers", sa.String(), nullable=True),
        sa.Column("attachments", sa.String(), nullable=True),
        sa.Column("mailer", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shorturls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("counter", sa.Integer(), nullable=False),
        sa.Column("latestcall_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "user_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("position_type", sa.String(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("position_type IN ('instruments', 'voices', 'choirjobs')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "position_type", "position_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("givenname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("auth_password", sa.String(), nullable=True),
        sa.Column("auth_remember_token", sa.String(), nullable=True),
        sa.Column("auth_lastlogin_provider", sa.String(), nullable=True),
        sa.Column("auth_lastlogin", sa.DateTime(), nullable=True),
        sa.Column("auth_lastsignal", sa.DateTime(), nullable=True),
        sa.Column("auth_lastlogout", sa.DateTime(), nullable=True),
        sa.Column("auth_locked", sa.Boolean(), nullable=False),
        sa.Column("administrator", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("surname", "givenname"),
    )
    op.create_table(
        "voices",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("voices")
    op.drop_table("users")
    op.drop_table("user_positions")
    op.drop_table("shorturls")
    op.drop_table("sent_emails")
    op.drop_table("scores")
    op.drop_table("roles")
    op.drop_table("request_logs")
    op.drop_table("propriumworks")
    op.drop_table("propriumelements")
    op.drop_index(
        "personal_access_tokens_tokenable_type_tokenable_id_index",
        table_name="personal_access_tokens",
    )
    op.drop_index(
        "personal_access_tokens_token_unique", table_name="personal_access_tokens"
    )
    op.drop_table("personal_access_tokens")
    op.drop_table("performances")
    op.drop_table("performance_rehearsals")
    op.drop_table("performance_proprium")
    op.drop_table("performance_positions")
    op.drop_index("password_resets_email_index", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_table("ordinariumworks")
    op.drop_table("ordinariumwork_positions")
    op.drop_table("oauth2_bindings")
    op.drop_table("locations")
    op.drop_table("instruments")
    op.drop_table("fees")
    op.drop_table("client_user_agents")
    op.drop_table("choirjobs")
    op.drop_table("bookings")
    op.drop_table("booking_requests")
    op.drop_table("booking_logs")
    op.drop_table("auth_logs")
    op.drop_table("artists")
    # ### end Alembic commands ###
